### ISSUE TITLE
"Tot" displayed

### ISSUE THREAD

**Issue by pascal-ballet** [jeancharles-roger/matrixstudio#19]
In the class MatrixStudio.java, the following line should be removed:
	public void refreshFields() {
		System.out.println("Tot ");   <=  remove this line

This line probably also induce the unexpected focus to the "Console" tab.

**Comment by jeancharles-roger** [comment]
I can't see it ...

**Comment by pascal-ballet** [comment]
Ah, yes. You put it the last thursday to try to find the display bug... So
not commited!


2016-10-11 16:50 GMT+02:00 Jean-Charles Roger <notifications@github.com>:
