### ISSUE TITLE
Multiple kernels for one task

### ISSUE THREAD

**Issue by jeancharles-roger** [jeancharles-roger/matrixstudio#2]
Tasks must be able to hold multiple kernels and run them in order.

For a first implementation, I proposes that the other parameters of the tasks (sizes and others) are common to all kernels for the tasks.

**Comment by pascal-ballet** [comment]
We need to call our group of tasks with a specific name which is not Task (offical and well-dfined name in OpenCL). I simply propose TaskGroup?

**Comment by jeancharles-roger** [comment]
I understand your concern, but all tasks in the scheduler will become task groups even if they only contain one kernel. So we need to change Task to TaskGroup and the concept of task will be removed from MS.

**Comment by pascal-ballet** [comment]
hmmm... pedagogically speaking, it's a concern if you call a task group simply a task. The name TaskGroup is not a good idea I'm afraid... Perhaps RepetitionBloc is better?

**Comment by jeancharles-roger** [comment]
I'm not fond of RepetitionBloc. 

The scheduler in MS is a scheduler diagram where tasks are considered as **OpenCL tasks**. But this is only a semantic shortcut. As the matter of fact they are **MS scheduler tasks**, so they can be abstracted from OpenCL tasks by adding some features. 

After all, it the all idea behind the scheduler.

**Comment by jeancharles-roger** [comment]
It's pushed, it need testing, especially the simulation part
