### ISSUE TITLE
Add an Export Java button

### ISSUE THREAD

**Issue by pascal-ballet** [jeancharles-roger/matrixstudio#22]
A button to export in Java all the project should be done (generates 3 files):
1) the host.java code (host ocl + matrices init + scheduler + simple matrix viewer (the current 3d viewer?)
2) the ocl.c code (libs + kernels)
3) compilation and execution commands in run.txt

**Comment by jeancharles-roger** [comment]
I think that we could provide a Java library that reads a model and offers a simple API to execute it and present it.

**Comment by pascal-ballet** [comment]
You're right. I did a first start in this direction. I close the issue.
